import { Inter } from "next/font/google";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";

import store from "@/store";
import { Provider } from "react-redux";
import "../styles/global.css";

config.autoAddCss = false;


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <Provider store={store}>
          {/* <header>
            <Link href="/login" >Login</Link>
          </header> */}
          {children}
          {/* <footer>
            Copyright &copy; TODO
          </footer> */}
        </Provider>

      </body>
    </html>
  );
}
